#!/usr/bin/env bash

if [ "$1" == "" ]; then
    dir="./config"
else
    dir="$1"
fi

CMD="./launch $dir"
T1="$CMD/1.cfg"
T2="$CMD/2.cfg"
T3="$CMD/3.cfg"
T4="$CMD/4.cfg"
T5="$CMD/5.cfg"
T6="$CMD/6.cfg"
T7="$CMD/7.cfg"
T8="echo 'Press [ctrl + b] and arrow keys to switch pane' && bash"



tmux new-session "$T1" \; \
    split-window -v "$T5" \; \
        split-window -h "$T7" \; \
            split-window -h "$T8" \; \
            select-pane -L \; \
        select-pane -L \; \
        split-window -h "$T6" \; \
    select-pane -U \; \
        split-window -h "$T3" \; \
            split-window -h "$T4" \; \
            select-pane -L \; \
        select-pane -L \; \
        split-window -h "$T2" \; \
    select-pane -L \; \

